page:
  name: page
  in: query
  required: false
  description: Paginanummer (1-based).
  schema:
    type: integer
    minimum: 1
    default: 1
perPage:
  name: perPage
  in: query
  required: false
  description: Aantal resultaten per pagina.
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20
organisation:
  name: organisation
  in: query
  required: false
  description: Filter op organisatie (bijvoorbeeld de organisation URI).
  schema:
    type: string
    format: uri