page:
  name: page
  in: query
  required: false
  description: Page number (1-based).
  schema:
    type: integer
    minimum: 1
    default: 1
perPage:
  name: perPage
  in: query
  required: false
  description: Number of results per page.
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 20
organisation:
  name: organisation
  in: query
  required: false
  description: Filter on organisation URI.
  schema:
    type: string
    format: uri
id:
  name: id
  in: path
  required: true
  description: Unique identifier of the resource.
  schema:
    type: string
q:
  name: q
  in: query
  required: true
  description: Search term.
  schema:
    type: string
